# Generated by Django 4.0.5 on 2022-09-20 12:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_mediaeducationsupervisor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['id'], 'verbose_name': 'Project category',
                     'verbose_name_plural': 'Project categories'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'ordering': [
                'id'], 'verbose_name': 'Target group', 'verbose_name_plural': 'Target groups'},
        ),
        migrations.AddField(
            model_name='project',
            name='democracy_project',
            field=models.BooleanField(
                default=False, verbose_name='Democracy project'),
        ),
    ]
