# Generated by Django 6.0.6 on 2026-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0030_mediafilesconfig_render_encode_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='When the read speed of this location was last measured.', null=True, verbose_name='Last Health Check'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='last_read_mbps',
            field=models.FloatField(blank=True, help_text='Read speed measured by the last health check. Empty means the location did not answer at all. Used to pick a reachable source when the same video exists on several locations.', null=True, verbose_name='Last Read Speed (MB/s)'),
        ),
    ]
