# Generated by Django 6.0.6 on 2026-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_inventoryunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('rented', 'Rented'), ('written_off', 'Written off'), ('defect', 'Defect'), ('retired', 'Retired')], default='in_stock', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('defect', 'Defect'), ('written_off', 'Written off'), ('retired', 'Retired')], default='in_stock', max_length=50, verbose_name='Status'),
        ),
    ]
