# Generated by Django 6.0.6 on 2026-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_inventoryitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode_attached',
            field=models.BooleanField(default=False, help_text='Check once the barcode label is stuck on the device.', verbose_name='Barcode label attached'),
        ),
    ]
