# Generated by Django 6.0.6 on 2026-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0019_exchangeconfig_same_state_channel_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='copy_chunk_size_mb',
            field=models.PositiveIntegerField(default=8, help_text='Video files are copied to the network share in chunks of this size. Smaller chunks report progress more finely but cost throughput; larger ones make the stall watchdog coarser. 8 MB is a good default.', verbose_name='Copy Chunk Size (MB)'),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='copy_stall_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Abort a copy that has written no byte for this long. Protects the Celery worker from hanging forever on an unresponsive share.', verbose_name='Copy Stall Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='export_lock_enabled',
            field=models.BooleanField(default=True, help_text='Skip items that another export task is already uploading, instead of letting two workers write the same file at once.', verbose_name='Prevent Concurrent Export of the Same Item'),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='export_source_failover_enabled',
            field=models.BooleanField(default=True, help_text='When the same video exists on several storage locations, read it from a reachable one instead of always from the highest-quality location. Only byte-identical copies are considered.', verbose_name='Export Source Failover'),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='export_source_min_read_mbps',
            field=models.FloatField(default=1.0, help_text='A storage location reading slower than this is treated as dead and skipped as an export source.', verbose_name='Minimum Source Read Speed (MB/s)'),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='export_tmp_cleanup_hours',
            field=models.PositiveIntegerField(default=24, help_text='Before each export, delete leftover .tmp_ files in the export directory older than this. Set to 0 to disable.', verbose_name='Export Temp File Cleanup (hours)'),
        ),
    ]
