# Generated by Django 4.0.5 on 2022-08-30 14:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetemplate',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='media_authority_exchange_allowed',
            field=models.BooleanField(
                null=True, verbose_name='Media Authority exchange allowed'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='repetitions_allowed',
            field=models.BooleanField(
                null=True, verbose_name='Repetitions allowed'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='store_in_ok_media_library',
            field=models.BooleanField(
                null=True, verbose_name='Store in OK media library'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='youth_protection_necessary',
            field=models.BooleanField(
                null=True, verbose_name='Youth protection necessary'),
        ),
    ]
